/* ============================================================================
   tests/cestis-core.test.js — automated verification of the shared data-core.

   Run with:  node tests/cestis-core.test.js
   No test framework required. Exits non-zero on the first failure so it can
   gate commits / CI. These tests cover the pure domain logic that used to be
   copy-pasted (and drift) across pages: stable identity, merge, dedupe,
   relink, the stable-id migration, and deletion tombstones.
   ============================================================================ */
'use strict';
var assert = require('assert');
var Core = require('../cestis-core.js');

var passed = 0;
function test(name, fn) {
  try { fn(); passed++; console.log('  ✓ ' + name); }
  catch (e) { console.error('  ✗ ' + name + '\n      ' + (e && e.message)); process.exitCode = 1; throw e; }
}

/* The app's original hash, reproduced here so we can assert cestis-core matches
   it exactly — guaranteeing ids stay compatible with anything already stored. */
function originalHash(str) {
  str = String(str == null ? '' : str);
  var h1 = 0xdeadbeef, h2 = 0x41c6ce57;
  for (var i = 0, ch; i < str.length; i++) {
    ch = str.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507) ^ Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507) ^ Math.imul(h1 ^ (h1 >>> 13), 3266489909);
  return (4294967296 * (2097151 & h2) + (h1 >>> 0)).toString(36);
}

console.log('cestis-core domain logic');

/* ---- hashing ---------------------------------------------------------- */
test('hashString matches the app\'s original algorithm', function () {
  ['', 'a', 'John Smith|welding', 'x'.repeat(500)].forEach(function (s) {
    assert.strictEqual(Core.hashString(s), originalHash(s), 'mismatch for: ' + s);
  });
});
test('hashString is deterministic', function () {
  assert.strictEqual(Core.hashString('repeat me'), Core.hashString('repeat me'));
});

/* ---- stable identity -------------------------------------------------- */
test('stableStudentId is identical for the same person regardless of other fields', function () {
  var a = { id: 'STU1700000000001', name: 'John Smith', course: 'Welding & Fabrication', email: 'j@x.com', progress: 80 };
  var b = { id: 'STU9999999999999', name: 'John Smith', course: 'Welding & Fabrication', progress: 5 };
  assert.strictEqual(Core.stableStudentId(a), Core.stableStudentId(b));
});
test('stableStudentId normalises case and whitespace', function () {
  assert.strictEqual(
    Core.stableStudentId({ name: '  John   Smith ', course: 'WELDING & fabrication' }),
    Core.stableStudentId({ name: 'john smith', course: 'welding & fabrication' })
  );
});
test('stableStudentId differs across people / courses', function () {
  var x = Core.stableStudentId({ name: 'John Smith', course: 'Welding & Fabrication' });
  assert.notStrictEqual(x, Core.stableStudentId({ name: 'Jane Smith', course: 'Welding & Fabrication' }));
  assert.notStrictEqual(x, Core.stableStudentId({ name: 'John Smith', course: 'Plumbing' }));
});
test('stableStudentId is null when there is no usable name', function () {
  assert.strictEqual(Core.stableStudentId({ name: '', course: 'Welding' }), null);
});

test('isAutoGeneratedId distinguishes machine ids from user ids and is idempotent-safe', function () {
  assert.strictEqual(Core.isAutoGeneratedId('STU' + Date.now()), true, 'timestamp id is auto');
  assert.strictEqual(Core.isAutoGeneratedId('STU' + Date.now() + Math.random()), true, 'timestamp+random id is auto');
  assert.strictEqual(Core.isAutoGeneratedId(''), true, 'blank is auto');
  assert.strictEqual(Core.isAutoGeneratedId(null), true, 'null is auto');
  // a deterministic stable id must NOT look auto, or stabilisation would loop
  assert.strictEqual(Core.isAutoGeneratedId(Core.stableStudentId({ name: 'A', course: 'C' })), false, 'stable id is not auto (idempotency)');
  assert.strictEqual(Core.isAutoGeneratedId('STU001'), false, 'short user id preserved');
  assert.strictEqual(Core.isAutoGeneratedId('ADMISSION-2024-014'), false, 'human id preserved');
});

/* ---- merge ------------------------------------------------------------ */
test('mergeStudentRecords prefers the newer record, backfills blanks from the older', function () {
  var older = { id: '1', name: 'A', course: 'C', lastModified: '2026-01-01', progress: 10, email: 'old@x.com', phone: '111' };
  var newer = { id: '2', name: 'A', course: 'C', lastModified: '2026-05-01', progress: 90, email: '', phone: '' };
  var m = Core.mergeStudentRecords(older, newer);
  assert.strictEqual(m.progress, 90, 'newer value wins');
  assert.strictEqual(m.email, 'old@x.com', 'blank in newer backfilled from older');
  assert.strictEqual(m.phone, '111');
});

test('mergeStudentRecords preserves cross-system link fields (schoolFeeId)', function () {
  var manual = { id: 'STU-1', name: 'A', course: 'C', lastModified: '2026-05-01', progress: 50 };
  var feeLinked = { id: 'SF-99', name: 'A', course: 'C', lastModified: '2026-01-01', schoolFeeId: '99', source: 'schoolfee' };
  var m = Core.mergeStudentRecords(manual, feeLinked);
  assert.strictEqual(m.schoolFeeId, '99', 'fee link survives merge into the newer manual record');
  assert.strictEqual(m.source, 'schoolfee');
});

/* ---- dedupe ----------------------------------------------------------- */
test('dedupeStudents collapses cross-device duplicates and maps old ids', function () {
  var list = [
    { id: 'STU-A', name: 'John Smith', course: 'Welding', lastModified: '2026-01-01', progress: 10, email: 'j@x.com' },
    { id: 'STU-B', name: 'john smith', course: 'welding', lastModified: '2026-05-01', progress: 90, email: '' },
    { id: 'STU-C', name: 'Jane Doe', course: 'Plumbing' }
  ];
  var r = Core.dedupeStudents(list);
  assert.strictEqual(r.students.length, 2, 'two unique people remain');
  assert.strictEqual(r.removed, 1);
  var john = r.students.filter(function (s) { return Core.normName(s.name) === 'john smith'; })[0];
  assert.strictEqual(john.progress, 90, 'kept newer progress');
  assert.strictEqual(john.email, 'j@x.com', 'backfilled email from duplicate');
  // every removed id should resolve to a surviving id
  Object.keys(r.idMap).forEach(function (old) {
    assert.ok(r.students.some(function (s) { return s.id === r.idMap[old]; }), 'idMap target survives: ' + old);
  });
});
test('dedupeStudents passes through records with no natural key', function () {
  var list = [{ id: '1', name: '', course: 'X' }, { id: '2', name: '', course: 'Y' }];
  var r = Core.dedupeStudents(list);
  assert.strictEqual(r.students.length, 2);
  assert.strictEqual(r.removed, 0);
});

/* ---- relink ----------------------------------------------------------- */
test('relinkDependentData remaps and dedups dependent arrays', function () {
  var idMap = { 'STU-B': 'STU-A' };
  var data = {
    userAccounts: [
      { username: 'a', studentDataId: 'STU-A', password: 'p', status: 'active' },
      { username: 'a2', studentDataId: 'STU-B' }
    ],
    attendanceRecords: [{ studentId: 'STU-B', date: '2026-01-01' }],
    certDownloadApprovals: [{ studentId: 'STU-A' }, { studentId: 'STU-B' }],
    examResults: [{ studentId: 'STU-B', score: 70 }]
  };
  Core.relinkDependentData(idMap, data);
  assert.strictEqual(data.attendanceRecords[0].studentId, 'STU-A');
  assert.strictEqual(data.examResults[0].studentId, 'STU-A');
  assert.strictEqual(data.certDownloadApprovals.length, 1, 'cert approvals deduped by studentId');
  assert.ok(data.userAccounts.length <= 2);
  data.userAccounts.forEach(function (u) { assert.strictEqual(u.studentDataId, 'STU-A'); });
});

/* ---- migration -------------------------------------------------------- */
test('migrateToStableIds assigns stable ids, collapses dups, relinks deps', function () {
  var data = {
    students: [
      { id: 'STU1700000000001', name: 'John Smith', course: 'Welding', lastModified: '2026-01-01', progress: 10 },
      { id: 'STU1700000000999', name: 'john smith', course: 'welding', lastModified: '2026-05-01', progress: 90 }
    ],
    userAccounts: [{ username: 'js', studentDataId: 'STU1700000000999' }],
    attendanceRecords: [{ studentId: 'STU1700000000001' }, { studentId: 'STU1700000000999' }]
  };
  var res = Core.migrateToStableIds(data);
  assert.strictEqual(data.students.length, 1, 'duplicate collapsed');
  var stable = Core.stableStudentId({ name: 'John Smith', course: 'Welding' });
  assert.strictEqual(data.students[0].id, stable, 'survivor got the stable id');
  assert.strictEqual(data.users === undefined, true);
  assert.strictEqual(data.userAccounts[0].studentDataId, stable, 'account relinked to stable id');
  data.attendanceRecords.forEach(function (r) { assert.strictEqual(r.studentId, stable, 'attendance relinked'); });
  assert.ok(res.changed);
});
test('migrateToStableIds is idempotent (second run changes nothing)', function () {
  var data = {
    students: [
      { id: 'STU-x', name: 'Amy Lee', course: 'Plumbing' },
      { id: 'STU-y', name: 'Bob Ray', course: 'Masonry' }
    ],
    userAccounts: [], attendanceRecords: []
  };
  Core.migrateToStableIds(data);
  var snapshot = JSON.stringify(data.students);
  var res2 = Core.migrateToStableIds(data);
  assert.strictEqual(JSON.stringify(data.students), snapshot, 'no further mutation');
  assert.strictEqual(res2.changed, false, 'reports no change on second run');
});

/* ---- integration: realistic mixed dataset ----------------------------- */
test('migration: fee-linked + manual + cross-device dup all collapse correctly', function () {
  var data = {
    students: [
      // Same person, three ways they could enter the system on different devices:
      { id: 'SF-99', name: 'Mary Jane', course: 'Cosmetology', schoolFeeId: '99', source: 'schoolfee', lastModified: '2026-01-01', progress: 0 },
      { id: 'STU-LEGACY-1', name: 'mary jane', course: 'cosmetology', lastModified: '2026-03-01', progress: 40, email: 'mary@x.com' },
      { id: 'STU1700000009999', name: 'Mary  Jane', course: 'Cosmetology', lastModified: '2026-05-01', progress: 75 },
      // A genuinely different person:
      { id: 'STU-2', name: 'Sam Okafor', course: 'Welding & Fabrication', lastModified: '2026-02-01' }
    ],
    userAccounts: [
      { username: 'mary', studentDataId: 'SF-99' },
      { username: 'mary2', studentDataId: 'STU-LEGACY-1' }
    ],
    attendanceRecords: [
      { studentId: 'SF-99' }, { studentId: 'STU-LEGACY-1' }, { studentId: 'STU1700000009999' }
    ],
    certDownloadApprovals: [{ studentId: 'STU-LEGACY-1' }],
    examResults: [{ studentId: 'STU1700000009999', score: 88 }]
  };
  var res = Core.migrateToStableIds(data);
  assert.ok(res.changed);
  assert.strictEqual(data.students.length, 2, 'Mary collapsed to one; Sam separate');

  var mary = data.students.filter(function (s) { return Core.normName(s.name) === 'mary jane'; })[0];
  var maryStable = Core.stableStudentId({ name: 'Mary Jane', course: 'Cosmetology' });
  assert.strictEqual(mary.id, maryStable, 'Mary has the deterministic stable id');
  assert.strictEqual(mary.progress, 75, 'kept newest progress');
  assert.strictEqual(mary.email, 'mary@x.com', 'backfilled email from an older copy');
  assert.strictEqual(mary.schoolFeeId, '99', 'fee link preserved through the collapse');

  // every dependent record now points at the single stable Mary id
  data.attendanceRecords.forEach(function (r) { assert.strictEqual(r.studentId, maryStable); });
  assert.strictEqual(data.examResults[0].studentId, maryStable);
  assert.strictEqual(data.certDownloadApprovals[0].studentId, maryStable);
  data.userAccounts.forEach(function (u) { assert.strictEqual(u.studentDataId, maryStable, 'accounts relinked'); });

  // second run is a no-op
  assert.strictEqual(Core.migrateToStableIds(data).changed, false);
});

/* ---- tombstones (with a mock store) ----------------------------------- */
test('tombstones record and detect deleted ids', function () {
  var mem = {};
  var mockStore = {
    getItem: function (k) { return k in mem ? mem[k] : null; },
    setItem: function (k, v) { mem[k] = String(v); }
  };
  assert.strictEqual(Core.isStudentDeleted('STU-Z', mockStore), false);
  Core.recordDeletedStudent('STU-Z', mockStore);
  assert.strictEqual(Core.isStudentDeleted('STU-Z', mockStore), true);
  // stable ids mean a re-synced copy of the same deleted student is still caught
  var sid = Core.stableStudentId({ name: 'Gone Person', course: 'Welding' });
  Core.recordDeletedStudent(sid, mockStore);
  assert.strictEqual(Core.isStudentDeleted(Core.stableStudentId({ name: 'gone person', course: 'WELDING' }), mockStore), true);
});

/* ---- change bus (drives reactive view refresh) ------------------------ */
test('bus delivers payloads to subscribers and off() unsubscribes', function () {
  var got = [];
  var unsub = Core.on('evt:x', function (p) { got.push(p); });
  Core.emit('evt:x', 1);
  Core.emit('evt:x', 2);
  unsub();
  Core.emit('evt:x', 3);
  assert.deepStrictEqual(got, [1, 2], 'received before unsubscribe only');
});
test('a throwing listener does not break the others', function () {
  var reached = false;
  Core.on('evt:y', function () { throw new Error('boom'); });
  Core.on('evt:y', function () { reached = true; });
  Core.emit('evt:y');
  assert.strictEqual(reached, true);
  // emitting an event with no listeners must not throw
  assert.doesNotThrow(function () { Core.emit('evt:nobody'); });
});

/* ---- master snapshot: build / verify ---------------------------------- */
test('buildSnapshot excludes sensitive keys and is checksum-verifiable', function () {
  var storeMap = {
    voctrain_students: JSON.stringify([{ id: 'STU-A', name: 'A', course: 'C' }]),
    cestisGoogleAccessToken: 'secret-token',
    voctrain_sessionUserId: 'USR-1',
    schoolFeeCloudFileId: 'file123',
    darkMode: 'true',
    cestiSchoolFeeStudents: JSON.stringify([{ id: 'SF-1', name: 'A' }])
  };
  var snap = Core.buildSnapshot(storeMap, { event: 'logout', savedBy: 'admin' });
  assert.ok(!('cestisGoogleAccessToken' in snap.store), 'token excluded');
  assert.ok(!('voctrain_sessionUserId' in snap.store), 'session excluded');
  assert.ok(!('schoolFeeCloudFileId' in snap.store), 'cloud file id excluded');
  assert.ok(!('darkMode' in snap.store), 'volatile ui flag excluded');
  assert.ok('voctrain_students' in snap.store && 'cestiSchoolFeeStudents' in snap.store, 'data kept');
  assert.strictEqual(snap.event, 'logout');
  assert.strictEqual(snap.counts.voctrain_students, 1);
  assert.strictEqual(Core.verifySnapshot(snap).ok, true, 'checksum verifies');
});
test('verifySnapshot detects tampering / corruption', function () {
  var snap = Core.buildSnapshot({ voctrain_students: JSON.stringify([{ id: 'X', name: 'n', course: 'c' }]) }, {});
  snap.store.voctrain_students = JSON.stringify([{ id: 'X', name: 'n', course: 'c' }, { id: 'Y', name: 'm', course: 'c' }]);
  assert.strictEqual(Core.verifySnapshot(snap).ok, false, 'mutated store fails checksum');
});
test('checksum is independent of key insertion order', function () {
  var a = Core.buildSnapshot({ voctrain_students: '[]', cestiSchoolFeeStudents: '[]' }, {});
  var b = Core.buildSnapshot({ cestiSchoolFeeStudents: '[]', voctrain_students: '[]' }, {});
  assert.strictEqual(a.checksum, b.checksum);
});

/* ---- master snapshot: data-loss report -------------------------------- */
test('dataLossReport finds records the snapshot has but local lost', function () {
  var snap = Core.buildSnapshot({
    voctrain_students: JSON.stringify([
      { id: 'STU-A', name: 'A', course: 'C' },
      { id: 'STU-B', name: 'B', course: 'C' },
      { id: 'STU-GONE', name: 'Deleted Person', course: 'C' }
    ])
  }, {});
  var local = {
    voctrain_students: JSON.stringify([{ id: 'STU-A', name: 'A', course: 'C' }]),
    voctrain_deletedStudentIds: JSON.stringify(['STU-GONE']) // intentionally deleted
  };
  var rep = Core.dataLossReport(snap, local);
  assert.strictEqual(rep.collections.voctrain_students.missingFromLocal, 1, 'only STU-B counts as lost');
  assert.deepStrictEqual(rep.missingLocally.voctrain_students, ['STU-B']);
  assert.strictEqual(rep.totalMissing, 1);
});

/* ---- master snapshot: reconcile (merge & repair) ---------------------- */
test('reconcileSnapshot restores missing records without resurrecting deletes', function () {
  var snap = Core.buildSnapshot({
    voctrain_students: JSON.stringify([
      { id: 'STU-A', name: 'A', course: 'C', progress: 10 },
      { id: 'STU-B', name: 'B', course: 'C' },
      { id: 'STU-GONE', name: 'Gone', course: 'C' }
    ]),
    voctrain_systemSettings: JSON.stringify({ theme: 'x' })
  }, {});
  var local = {
    voctrain_students: JSON.stringify([{ id: 'STU-A', name: 'A', course: 'C', progress: 99 }]),
    voctrain_deletedStudentIds: JSON.stringify(['STU-GONE']),
    voctrain_systemSettings: '' // empty locally -> should be restored
  };
  var res = Core.reconcileSnapshot(snap, local);
  assert.ok(res.changed);
  var students = JSON.parse(res.store.voctrain_students);
  var ids = students.map(function (s) { return s.id; }).sort();
  assert.deepStrictEqual(ids, ['STU-A', 'STU-B'], 'B restored, GONE not resurrected');
  var a = students.filter(function (s) { return s.id === 'STU-A'; })[0];
  assert.strictEqual(a.progress, 99, 'newer local edit preserved, not overwritten by snapshot');
  assert.strictEqual(res.recoveredStudents, 1);
  assert.strictEqual(res.store.voctrain_systemSettings, JSON.stringify({ theme: 'x' }), 'empty config restored');
});
test('reconcileSnapshot unions tombstones and drops a now-tombstoned local student', function () {
  // Device A deleted Mary -> the snapshot carries the tombstone but not Mary.
  // Device B still has Mary locally and no tombstone. After reconcile, B must
  // gain the tombstone AND drop Mary (deleted data cannot re-emerge anywhere).
  var maryId = 'STU-MARY';
  var snap = Core.buildSnapshot({
    voctrain_students: JSON.stringify([{ id: 'STU-keep', name: 'Sam', course: 'Welding' }]),
    voctrain_deletedStudentIds: JSON.stringify([maryId])
  }, {});
  var local = {
    voctrain_students: JSON.stringify([
      { id: maryId, name: 'Mary', course: 'Cosmetology' },
      { id: 'STU-keep', name: 'Sam', course: 'Welding' }
    ]),
    voctrain_deletedStudentIds: JSON.stringify([])
  };
  var res = Core.reconcileSnapshot(snap, local);
  assert.ok(res.changed);
  var ids = JSON.parse(res.store.voctrain_students).map(function (s) { return s.id; });
  assert.strictEqual(ids.indexOf(maryId), -1, 'tombstoned Mary dropped on device B');
  assert.ok(ids.indexOf('STU-keep') !== -1, 'Sam kept');
  assert.ok(JSON.parse(res.store.voctrain_deletedStudentIds).indexOf(maryId) !== -1, 'tombstone propagated to device B');
  assert.ok(res.droppedTombstoned >= 1);
});
test('reconcileSnapshot is a no-op when local already has everything', function () {
  var data = { voctrain_students: JSON.stringify([{ id: 'STU-A', name: 'A', course: 'C' }]) };
  var snap = Core.buildSnapshot(data, {});
  var res = Core.reconcileSnapshot(snap, data);
  assert.strictEqual(res.changed, false);
});

/* ---- tombstone resurrection prevention -------------------------------- */
test('dropTombstonedStudents removes a student matched by its current id', function () {
  var students = [{ id: 'STU-A', name: 'A', course: 'C' }, { id: 'STU-B', name: 'B', course: 'C' }];
  var del = { 'STU-A': true };
  var r = Core.dropTombstonedStudents(students, del);
  assert.strictEqual(r.removed, 1);
  assert.deepStrictEqual(r.students.map(function (s) { return s.id; }), ['STU-B']);
  assert.deepStrictEqual(r.droppedIds, ['STU-A']);
});
test('dropTombstonedStudents catches a resurrected copy carrying a DIFFERENT id', function () {
  // Student was deleted; its stable id was tombstoned. A cloud/fee copy returns
  // under a legacy id but the same name+course -> must still be dropped.
  var person = { name: 'Mary Jane', course: 'Cosmetology' };
  var stable = Core.stableStudentId(person);
  var resurrected = { id: 'SF-legacy-999', name: 'mary  jane', course: 'COSMETOLOGY' };
  var r = Core.dropTombstonedStudents([resurrected, { id: 'STU-keep', name: 'Sam', course: 'Welding' }], (function () { var m = {}; m[stable] = true; return m; })());
  assert.strictEqual(r.removed, 1, 'resurrected copy dropped via stable-id match');
  assert.deepStrictEqual(r.students.map(function (s) { return s.id; }), ['STU-keep']);
});
test('dropTombstonedStudents keeps everything when nothing is tombstoned', function () {
  var students = [{ id: 'STU-A', name: 'A', course: 'C' }];
  var r = Core.dropTombstonedStudents(students, {});
  assert.strictEqual(r.removed, 0);
  assert.strictEqual(r.students.length, 1);
});
test('end-to-end: tombstoned student survives neither migration nor a re-add', function () {
  // Simulate: delete Mary (tombstone her stable id), then a sync re-adds her
  // under a fresh unstable id. After stabilize + drop she must be gone.
  var mary = { name: 'Mary Jane', course: 'Cosmetology' };
  var stable = Core.stableStudentId(mary);
  var del = {}; del[stable] = true;
  var students = [
    { id: 'STU-1700000000001', name: 'Mary Jane', course: 'Cosmetology' }, // re-added copy
    { id: 'STU-keep', name: 'Sam Okafor', course: 'Welding & Fabrication' }
  ];
  // migrate first (as the app does, which restabilises every id), then drop tombstoned
  var bundle = { students: students };
  Core.migrateToStableIds(bundle);
  var r = Core.dropTombstonedStudents(bundle.students, del);
  assert.strictEqual(r.students.length, 1, 'only one student remains');
  assert.strictEqual(Core.normName(r.students[0].name), 'sam okafor', 'Mary stays deleted, Sam remains');
});

/* ---- catalogue -------------------------------------------------------- */
test('catalogue is shared and freshSkillAreas returns an independent copy', function () {
  assert.strictEqual(Core.SKILL_AREAS.length, 20);
  var a = Core.freshSkillAreas();
  a[0].students = 999;
  assert.strictEqual(Core.SKILL_AREAS[0].students, 0, 'mutating a copy must not corrupt the source');
});

/* ---- quarter engine --------------------------------------------------- */
test('deriveQuarter buckets dates into the correct FY and quarter', function () {
  assert.deepStrictEqual(Core.deriveQuarter('2026-04-01'), { fy: '2026/2027', q: 1 }, 'Apr -> Q1 of new FY');
  assert.deepStrictEqual(Core.deriveQuarter('2026-06-30'), { fy: '2026/2027', q: 1 }, 'Jun -> Q1');
  assert.deepStrictEqual(Core.deriveQuarter('2026-07-01'), { fy: '2026/2027', q: 2 }, 'Jul -> Q2');
  assert.deepStrictEqual(Core.deriveQuarter('2026-12-31'), { fy: '2026/2027', q: 3 }, 'Dec -> Q3');
  assert.deepStrictEqual(Core.deriveQuarter('2027-01-15'), { fy: '2026/2027', q: 4 }, 'Jan -> Q4 of SAME FY span');
  assert.deepStrictEqual(Core.deriveQuarter('2027-03-31'), { fy: '2026/2027', q: 4 }, 'Mar -> Q4');
  assert.deepStrictEqual(Core.deriveQuarter('2027-04-01'), { fy: '2027/2028', q: 1 }, 'next Apr rolls the FY');
});

test('deriveQuarter handles ISO timestamps, Date objects and bad input', function () {
  assert.deepStrictEqual(Core.deriveQuarter('2026-10-05T08:30:00.000Z'), { fy: '2026/2027', q: 3 }, 'ISO timestamp');
  assert.deepStrictEqual(Core.deriveQuarter(new Date(2026, 3, 10)), { fy: '2026/2027', q: 1 }, 'Date object (April)');
  assert.strictEqual(Core.deriveQuarter(''), null, 'empty -> null');
  assert.strictEqual(Core.deriveQuarter(null), null, 'null -> null');
  assert.strictEqual(Core.deriveQuarter('not-a-date'), null, 'garbage -> null');
});

test('quarter labels and calendar year are correct', function () {
  assert.strictEqual(Core.quarterCalendarYear('2026/2027', 1), 2026, 'Q1 is in the first year');
  assert.strictEqual(Core.quarterCalendarYear('2026/2027', 4), 2027, 'Q4 (Jan-Mar) is in the second year');
  assert.strictEqual(Core.quarterShortLabel('2026/2027', 1), 'Q1 · Apr–Jun');
  assert.strictEqual(Core.quarterPeriodLabel('2026/2027', 4), 'Jan–Mar 2027');
  assert.strictEqual(Core.fyLabel('2026/2027'), 'FY 2026/2027');
});

test('quarterKey namespaces a base storage key per quarter', function () {
  assert.strictEqual(Core.quarterKey('voctrain_attendance', '2026/2027', 1), 'voctrain_attendance::2026/2027_Q1');
});

test('recordInQuarter filters by date, and honours explicit fy/quarter fields', function () {
  assert.strictEqual(Core.recordInQuarter({ date: '2026-05-10' }, '2026/2027', 1), true, 'May date in Q1');
  assert.strictEqual(Core.recordInQuarter({ date: '2026-08-10' }, '2026/2027', 1), false, 'Aug date not in Q1');
  // explicit fields win over the derived date
  assert.strictEqual(Core.recordInQuarter({ date: '2026-08-10', fy: '2026/2027', quarter: 1 }, '2026/2027', 1), true, 'explicit fy/quarter override');
  // custom date field name
  assert.strictEqual(Core.recordInQuarter({ clockIn: '2026-11-02T09:00:00Z' }, '2026/2027', 3, 'clockIn'), true, 'custom date field');
});

test('sameQuarter compares FY+quarter pairs null-safely', function () {
  assert.strictEqual(Core.sameQuarter({ fy: '2026/2027', q: 2 }, { fy: '2026/2027', q: 2 }), true);
  assert.strictEqual(Core.sameQuarter({ fy: '2026/2027', q: 2 }, { fy: '2026/2027', q: 3 }), false);
  assert.strictEqual(Core.sameQuarter(null, { fy: '2026/2027', q: 2 }), false);
});

/* ---- course duration -------------------------------------------------- */
var CD = Core.courseDuration;

test('courseDuration.status classifies not-started / active / ended / no-dates', function () {
  assert.strictEqual(CD.status('2026-01-01', '2026-12-31', '2025-12-31'), 'not-started');
  assert.strictEqual(CD.status('2026-01-01', '2026-12-31', '2026-06-15'), 'active');
  assert.strictEqual(CD.status('2026-01-01', '2026-12-31', '2027-01-01'), 'ended');
  assert.strictEqual(CD.status('', '', '2026-06-15'), 'no-dates');
  // boundary days are inclusive
  assert.strictEqual(CD.status('2026-01-01', '2026-12-31', '2026-01-01'), 'active', 'start day inclusive');
  assert.strictEqual(CD.status('2026-01-01', '2026-12-31', '2026-12-31'), 'active', 'end day inclusive');
});

test('courseDuration.isActive treats a dateless course as open and an ended course as closed', function () {
  assert.strictEqual(CD.isActive('', '', '2026-06-15'), true);
  assert.strictEqual(CD.isActive('2026-01-01', '2026-12-31', '2026-06-15'), true);
  assert.strictEqual(CD.isActive('2026-01-01', '2026-12-31', '2027-02-01'), false);
});

test('courseDuration.grantExpiry gives 12h for half day and 24h for full day', function () {
  var now = 1000000000000;
  assert.strictEqual(CD.grantExpiry(now, 'half'), now + 12 * 60 * 60 * 1000);
  assert.strictEqual(CD.grantExpiry(now, 'full'), now + 24 * 60 * 60 * 1000);
});

test('courseDuration.permissionActiveAt detects an unexpired reopen permission', function () {
  var now = 2000000;
  assert.strictEqual(CD.permissionActiveAt([{ expiresAtMs: now + 1000 }], now), true);
  assert.strictEqual(CD.permissionActiveAt([{ expiresAtMs: now - 1000 }], now), false, 'expired');
  assert.strictEqual(CD.permissionActiveAt([], now), false);
  assert.strictEqual(CD.permissionActiveAt(null, now), false);
});

test('courseDuration.isRegisterOpen: open while active, closed after end, reopened by permission', function () {
  var active = { startDate: '2026-01-01', endDate: '2026-12-31' };
  var ended  = { startDate: '2026-01-01', endDate: '2026-12-31' };
  assert.strictEqual(CD.isRegisterOpen(active, '2026-06-15', 0), true, 'active course open');
  assert.strictEqual(CD.isRegisterOpen(ended, '2027-02-01', 5000), false, 'ended course closed');
  var withPerm = { startDate: '2026-01-01', endDate: '2026-12-31', instructorPermissions: [{ expiresAtMs: 9000 }] };
  assert.strictEqual(CD.isRegisterOpen(withPerm, '2027-02-01', 5000), true, 'unexpired permission reopens');
  assert.strictEqual(CD.isRegisterOpen(withPerm, '2027-02-01', 9000), false, 'expired permission no longer reopens');
  assert.strictEqual(CD.isRegisterOpen(null, '2027-02-01', 5000), true, 'no course = open');
});

test('courseDuration.prunePermissions drops expired grants only', function () {
  var now = 1000;
  var pruned = CD.prunePermissions([{ expiresAtMs: 500 }, { expiresAtMs: 1500 }, { expiresAtMs: 2000 }], now);
  assert.strictEqual(pruned.length, 2);
  assert.deepStrictEqual(pruned.map(function (p) { return p.expiresAtMs; }), [1500, 2000]);
});

/* ---- login/cert survival across sync (regression) --------------------- */
console.log('\ncestis-core account & approval survival');

test('accountLoginScore: a real active login always beats a disabled placeholder', function () {
  var real = { password: 'hash', status: 'active', email: 'a@b.com' };
  var placeholder = { password: '', status: 'disabled' };
  assert.ok(Core.accountLoginScore(real) > Core.accountLoginScore(placeholder));
  // pending beats disabled; both password-less
  assert.ok(Core.accountLoginScore({ password: '', status: 'pending' }) > Core.accountLoginScore(placeholder));
});

test('approvalScore: approved always beats not-approved, then recency wins', function () {
  var approved = { approved: true, approvedDate: '2026-01-01T00:00:00Z' };
  var notApproved = { approved: false, approvedDate: '2026-09-01T00:00:00Z' };
  assert.ok(Core.approvalScore(approved) > Core.approvalScore(notApproved), 'approved beats newer-but-unapproved');
  var older = { approved: true, approvedDate: '2026-01-01T00:00:00Z' };
  var newer = { approved: true, approvedDate: '2026-06-01T00:00:00Z' };
  assert.ok(Core.approvalScore(newer) > Core.approvalScore(older), 'newer approval wins the tie');
});

test('relinkDependentData: keeps the best account per student regardless of order', function () {
  var real = { id: 'USR-REAL', role: 'student', username: 'jsmith', password: 'hash', status: 'active', studentDataId: 'STU-1' };
  var placeholder = { id: 'USR-SYNC-STU-1', role: 'student', username: 'john.smith', password: '', status: 'disabled', studentDataId: 'STU-1' };
  // placeholder FIRST — old first-wins logic would have kept it and blocked login
  var d1 = { userAccounts: [placeholder, real] };
  Core.relinkDependentData({ 'ignore': 'x' }, d1);
  assert.strictEqual(d1.userAccounts.length, 1);
  assert.strictEqual(d1.userAccounts[0].id, 'USR-REAL');
  // real FIRST — same outcome, proving order independence
  var d2 = { userAccounts: [Object.assign({}, real), Object.assign({}, placeholder)] };
  Core.relinkDependentData({ 'ignore': 'x' }, d2);
  assert.strictEqual(d2.userAccounts.length, 1);
  assert.strictEqual(d2.userAccounts[0].id, 'USR-REAL');
});

test('relinkDependentData: keeps the approved certificate approval, not the first', function () {
  var unapproved = { studentId: 'STU-1', approved: false, approvedDate: '2026-01-01T00:00:00Z' };
  var approved = { studentId: 'STU-1', approved: true, approvedDate: '2026-02-01T00:00:00Z' };
  var d = { certDownloadApprovals: [unapproved, approved] };
  Core.relinkDependentData({ 'ignore': 'x' }, d);
  assert.strictEqual(d.certDownloadApprovals.length, 1);
  assert.strictEqual(d.certDownloadApprovals[0].approved, true);
});

test('reconcileSnapshot: re-links accounts & approvals through collapsed student ids', function () {
  // Local device: student STU-OLD, plus an account and an approval pointing at it.
  // Another device's snapshot has the SAME person under STU-NEW with a newer
  // lastModified, so the dedupe keeps STU-NEW and drops STU-OLD.
  var local = {
    voctrain_students: JSON.stringify([{ id: 'STU-OLD', name: 'John Smith', course: 'Welding & Fabrication', lastModified: '2026-01-01T00:00:00Z' }]),
    voctrain_users: JSON.stringify([{ id: 'USR-1', role: 'student', username: 'jsmith', password: 'hash', status: 'active', studentDataId: 'STU-OLD' }]),
    voctrain_certDownloadApprovals: JSON.stringify([{ id: 'CDA-STU-OLD', studentId: 'STU-OLD', approved: true }])
  };
  var snapshot = { store: {
    voctrain_students: JSON.stringify([{ id: 'STU-NEW', name: 'John Smith', course: 'Welding & Fabrication', lastModified: '2026-06-01T00:00:00Z' }])
  } };
  var res = Core.reconcileSnapshot(snapshot, local);
  var students = JSON.parse(res.store.voctrain_students);
  var accounts = JSON.parse(res.store.voctrain_users);
  var approvals = JSON.parse(res.store.voctrain_certDownloadApprovals);
  assert.strictEqual(students.length, 1, 'the two duplicate students collapse to one');
  var survivingId = students[0].id;
  assert.strictEqual(accounts[0].studentDataId, survivingId, 'account follows the surviving student id (not left dangling)');
  assert.strictEqual(approvals[0].studentId, survivingId, 'approval follows the surviving student id');
  // The account must still resolve to a real student — the reported login/cert bug
  // was exactly this link going stale after a sync.
  assert.ok(students.some(function (s) { return s.id === accounts[0].studentDataId; }), 'no dangling account link');
});

/* ---- LMS <-> School Fee twin linking ---------------------------------- */
console.log('\nStudent Progress <-> School Fee twin linking');

test('isFeeTwin: matches on the explicit lmsId back-link', function () {
  var lms = { id: 'STU-abc', name: 'John Smith', course: 'Welding' };
  var fee = { id: '2024-001', lmsId: 'STU-abc', name: 'John Smith', skillArea: 'Welding' };
  assert.ok(Core.isFeeTwin(lms, fee));
});

test('isFeeTwin: matches on a shared stable id and on the SF- twin id', function () {
  var sid = Core.stableStudentId({ name: 'John Smith', course: 'Welding' });
  assert.ok(Core.isFeeTwin({ id: sid, name: 'John Smith', course: 'Welding' }, { id: sid, name: 'John Smith' }));
  assert.ok(Core.isFeeTwin({ id: 'SF-9', name: 'John Smith', course: 'Welding' }, { id: '9', name: 'Someone Else' }));
});

test('isFeeTwin: matches on name + course when nothing is linked yet', function () {
  var lms = { id: 'STU-1', name: 'John  Smith', course: 'Welding' };
  assert.ok(Core.isFeeTwin(lms, { id: 'F1', name: 'john smith', skillArea: 'welding' }));
  assert.ok(!Core.isFeeTwin(lms, { id: 'F1', name: 'John Smith', skillArea: 'Plumbing' }), 'different course is a different person');
  assert.ok(!Core.isFeeTwin(lms, { id: 'F1', name: 'Jane Smith', skillArea: 'Welding' }));
});

test('isFeeTwin: a rename still finds the fee record via the pre-edit identity', function () {
  // This is the reported bug: renaming in Student Progress left School Fee on the
  // old name. The name no longer matches AND the stable id (a hash of
  // name+course) has moved, so without `was` the twin is unreachable.
  var oldId = Core.stableStudentId({ name: 'Jon Smith', course: 'Welding' });
  var newId = Core.stableStudentId({ name: 'John Smith', course: 'Welding' });
  assert.notStrictEqual(oldId, newId, 'renaming moves the stable id');
  var renamed = { id: newId, name: 'John Smith', course: 'Welding' };
  var fee = { id: oldId, name: 'Jon Smith', skillArea: 'Welding' };
  assert.ok(!Core.isFeeTwin(renamed, fee), 'unreachable without the previous identity');
  assert.ok(Core.isFeeTwin(renamed, fee, { id: oldId, name: 'Jon Smith', course: 'Welding' }),
    'found once the caller passes what the student was called before');
});

test('isFeeTwin: never matches unrelated people', function () {
  assert.ok(!Core.isFeeTwin({ id: 'A', name: 'John Smith', course: 'Welding' },
                            { id: 'B', name: 'Mary Brown', skillArea: 'Cosmetology' },
                            { id: 'C', name: 'Jon Smith', course: 'Welding' }));
  assert.ok(!Core.isFeeTwin(null, { id: 'B' }));
  assert.ok(!Core.isFeeTwin({ id: 'A' }, null));
});

/* ---- The fee page may not move a trainee, or invent a programme --------- */
console.log('\nMirroring a School Fee record onto the dashboard');

var CENTRES = [
  { id: 1, name: 'Welding and Fabrication Level 2', startDate: '2026-01-01', endDate: '2027-06-30' },
  { id: 2, name: 'Electrical Installation Level 2', startDate: '2026-01-01', endDate: '2027-06-30' }
];
function mirror(fee, lms) {
  return Core.lmsMirrorTarget(fee, lms, CENTRES,
    { findCentre: Core.enrolment.findCentre, on: '2026-06-01' });
}

test('a trainee already on the dashboard is never moved to another programme', function () {
  // The reported bug: the same person, filed under the fee page's own programme
  // name, read as a stranger — so a SECOND record was created for them under
  // that name and the Centre saw trainees on programmes nobody enrolled them in.
  var lms = [{ id: 'STU-1', name: 'Ann Brown', course: 'Electrical Installation Level 2' }];
  var t = mirror({ id: 'F1', name: 'Ann Brown', skillArea: 'Welding and Fabrication Level 2' }, lms);
  assert.strictEqual(t.action, 'link', 'linked, never created');
  assert.strictEqual(t.reason, 'already-enrolled-elsewhere');
  assert.strictEqual(t.match.id, 'STU-1');
  assert.strictEqual(t.course, 'Electrical Installation Level 2', 'the programme stays the dashboard\'s');
  assert.strictEqual(lms.length, 1, 'no second record is proposed');
});

test('the same person on the same programme is the ordinary twin link', function () {
  var lms = [{ id: 'STU-1', name: 'Ann Brown', course: 'Welding and Fabrication Level 2' }];
  var t = mirror({ id: 'F1', name: 'ann  brown', skillArea: 'Welding and Fabrication Level 2' }, lms);
  assert.strictEqual(t.action, 'link');
  assert.strictEqual(t.reason, 'twin');
});

test('a programme with no training centre is not mirrored at all', function () {
  // The fee page may price any programme it likes; the dashboard's roster is
  // VocTrain's, so a fee-only programme stays a fee record.
  var t = mirror({ id: 'F2', name: 'Ben Cole', skillArea: 'Carpentry L1' }, []);
  assert.strictEqual(t.action, 'skip');
  assert.strictEqual(t.reason, 'no-training-centre');
  assert.strictEqual(t.course, '');
});

test('a new trainee is mirrored under the training centre\'s own name', function () {
  var t = mirror({ id: 'F3', name: 'Cy Dean', skillArea: 'WELDING L2' }, []);
  assert.strictEqual(t.action, 'create');
  assert.strictEqual(t.course, 'Welding and Fabrication Level 2',
    'the fee side\'s spelling resolves to the centre\'s own name');
  assert.strictEqual(t.centreCourse, 'Welding and Fabrication Level 2');
});

test('the centre\'s name is offered for a blank dashboard programme, and only then', function () {
  var lms = [{ id: 'STU-1', name: 'Ann Brown', course: '' }];
  var t = mirror({ id: 'F1', name: 'Ann Brown', skillArea: 'WELDING L2' }, lms);
  assert.strictEqual(t.action, 'link');
  assert.strictEqual(t.centreCourse, 'Welding and Fabrication Level 2', 'available to fill a blank');

  var lms2 = [{ id: 'STU-2', name: 'Dee East', course: 'Electrical Installation Level 2' }];
  var t2 = mirror({ id: 'F4', name: 'Dee East', skillArea: 'Carpentry L1' }, lms2);
  assert.strictEqual(t2.centreCourse, '', 'a fee-only programme offers nothing to fill it with');
  assert.strictEqual(t2.course, 'Electrical Installation Level 2', 'and their programme is untouched');
});

test('the mirror the other way never duplicates a person either', function () {
  // A transfer, or the fee page pricing intakes by their key, leaves the two
  // sides naming the same trainee's programme differently. Matching on the
  // programme as well as the name minted a second, fee-less record for them.
  var fee = [{ id: 'F1', name: 'Ann Brown', skillArea: '02. Welding and Fabrication', totalPaid: 5000 }];
  var t = Core.feeMirrorTarget({ id: 'STU-1', name: 'Ann Brown', course: 'Welding and Fabrication' }, fee);
  assert.strictEqual(t.action, 'link', 'linked, never created');
  // The keyed spelling and the bare spelling of ONE centre are now recognised
  // as the same programme outright, so this is the ordinary twin link — it no
  // longer needs the weaker name-only fallback.
  assert.strictEqual(t.reason, 'twin');
  assert.strictEqual(t.match.id, 'F1');

  // Two DIFFERENT intakes of the programme, though, are two different things:
  // same person's name keyed to another intake links only by the name fallback,
  // never as a programme match.
  var other = Core.feeMirrorTarget({ id: 'STU-1', name: 'Ann Brown', course: '09. Welding and Fabrication' }, fee);
  assert.strictEqual(other.action, 'link', 'still linked — being the same person is enough');
  assert.strictEqual(other.reason, 'same-person-other-programme',
    'but keys 02 and 09 are different intakes, not the same programme');

  var linked = Core.feeMirrorTarget({ id: 'STU-1', name: 'Ann Brown', course: '02. Welding and Fabrication' }, fee);
  assert.strictEqual(linked.reason, 'twin', 'and matching programmes are the ordinary twin link');

  var fresh = Core.feeMirrorTarget({ id: 'STU-9', name: 'Nobody Known', course: 'Plumbing' }, fee);
  assert.strictEqual(fresh.action, 'create', 'somebody genuinely new does get a fee record');

  assert.strictEqual(Core.feeMirrorTarget({ id: 'X', name: '' }, fee).action, 'skip', 'no name, no mirror');
  assert.strictEqual(Core.feeMirrorTarget(null, fee).action, 'skip', 'null-safe');
  assert.strictEqual(Core.feeMirrorTarget({ name: 'Ann Brown' }, null).action, 'create', 'null list is safe');
});

test('a record with no name is never mirrored', function () {
  assert.strictEqual(mirror({ id: 'F5', name: '', skillArea: 'WELDING L2' }, []).action, 'skip');
  assert.strictEqual(Core.lmsMirrorTarget(null, [], CENTRES, {}).action, 'skip');
});

test('mirroring is safe with no centres and no resolver', function () {
  assert.strictEqual(Core.lmsMirrorTarget({ name: 'Ann Brown', skillArea: 'X' }, [], [], {}).action, 'skip');
  assert.strictEqual(Core.lmsMirrorTarget({ name: 'Ann Brown', skillArea: 'X' }, null, null,
    { findCentre: Core.enrolment.findCentre }).action, 'skip');
});

test('editedAt: reads either system\'s timestamp, newest field first', function () {
  assert.strictEqual(Core.editedAt(null), 0);
  assert.strictEqual(Core.editedAt({}), 0);
  assert.strictEqual(Core.editedAt({ createdAt: 'not a date' }), 0);
  assert.strictEqual(Core.editedAt({ createdAt: '2026-01-01T00:00:00Z' }), Date.parse('2026-01-01T00:00:00Z'));
  assert.strictEqual(Core.editedAt({ updatedAt: '2026-02-01T00:00:00Z', createdAt: '2026-01-01T00:00:00Z' }),
    Date.parse('2026-02-01T00:00:00Z'));
  assert.strictEqual(Core.editedAt({ lastModified: '2026-03-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' }),
    Date.parse('2026-03-01T00:00:00Z'));
});

test('shouldAdoptName: a newer rename propagates, an older one never reverts', function () {
  var older = { name: 'Jon Smith', lastModified: '2026-01-01T00:00:00Z' };
  var newer = { name: 'John Smith', updatedAt: '2026-06-01T00:00:00Z' };
  assert.ok(Core.shouldAdoptName(newer, older), 'the more recently edited side wins');
  assert.ok(!Core.shouldAdoptName(older, newer), 'and the stale side does not overwrite it');
});

test('shouldAdoptName: ignores blank names and no-op differences', function () {
  var dst = { name: 'John Smith', lastModified: '2026-01-01T00:00:00Z' };
  assert.ok(!Core.shouldAdoptName({ name: '', lastModified: '2026-09-01T00:00:00Z' }, dst), 'never blanks a name');
  assert.ok(!Core.shouldAdoptName({ name: '   ', lastModified: '2026-09-01T00:00:00Z' }, dst));
  assert.ok(!Core.shouldAdoptName({ name: ' john   smith ', lastModified: '2026-09-01T00:00:00Z' }, dst),
    'same name, differently spaced, is not a change');
  assert.ok(!Core.shouldAdoptName(null, dst));
  assert.ok(!Core.shouldAdoptName({ name: 'X' }, null));
});

test('shouldAdoptName: an undated record yields to one carrying a timestamp', function () {
  assert.ok(Core.shouldAdoptName({ name: 'John Smith', lastModified: '2026-06-01T00:00:00Z' }, { name: 'Jon Smith' }));
  assert.ok(!Core.shouldAdoptName({ name: 'Jon Smith' }, { name: 'John Smith', updatedAt: '2026-06-01T00:00:00Z' }));
});

test('shouldAdoptName: converges — once adopted, the reverse push is a no-op', function () {
  var lms = { name: 'John Smith', lastModified: '2026-06-01T00:00:00Z' };
  var fee = { name: 'Jon Smith', updatedAt: '2026-01-01T00:00:00Z' };
  assert.ok(Core.shouldAdoptName(lms, fee));
  fee.name = lms.name; fee.updatedAt = lms.lastModified;
  assert.ok(!Core.shouldAdoptName(fee, lms), 'no ping-pong back to the dashboard');
  assert.ok(!Core.shouldAdoptName(lms, fee), 'and no second pass in the original direction');
});

test('syncTwinFields: carries every shared detail, not just the name', function () {
  var lms = { name: 'John Smith', email: 'j@x.com', phone: '876-555-1111', gender: 'Male',
              dob: '1999-04-02', address: '12 Hope Rd', trn: '123-456-789',
              lastModified: '2026-06-01T00:00:00Z' };
  var fee = { name: 'Jon Smith', createdAt: '2026-01-01T00:00:00Z' };
  var changed = Core.syncTwinFields(lms, fee, 'lms->fee');
  assert.deepStrictEqual(fee.name, 'John Smith');
  assert.deepStrictEqual(fee.email, 'j@x.com');
  assert.deepStrictEqual(fee.contact, '876-555-1111');
  assert.deepStrictEqual(fee.dateOfBirth, '1999-04-02');
  assert.deepStrictEqual(fee.address, '12 Hope Rd');
  assert.deepStrictEqual(fee.nationalId, '123-456-789');
  assert.strictEqual(changed.length, 7);
});

test('syncTwinFields: maps back the other way', function () {
  var fee = { name: 'Mary Brown', contact: '876-555-2222', dateOfBirth: '2001-08-09',
              nationalId: 'TRN-9', updatedAt: '2026-06-01T00:00:00Z' };
  var lms = { name: 'Mary Brown', lastModified: '2026-01-01T00:00:00Z' };
  Core.syncTwinFields(fee, lms, 'fee->lms');
  assert.strictEqual(lms.phone, '876-555-2222');
  assert.strictEqual(lms.dob, '2001-08-09');
  assert.strictEqual(lms.trn, 'TRN-9');
});

test('syncTwinFields: never wipes the other side with a blank it does not hold', function () {
  var lms = { name: 'John Smith', email: '', phone: null, lastModified: '2026-06-01T00:00:00Z' };
  var fee = { name: 'John Smith', email: 'kept@x.com', contact: '876-555-3333',
              address: '9 Main St', createdAt: '2026-01-01T00:00:00Z' };
  var changed = Core.syncTwinFields(lms, fee, 'lms->fee');
  assert.deepStrictEqual(changed, [], 'nothing to copy');
  assert.strictEqual(fee.email, 'kept@x.com');
  assert.strictEqual(fee.contact, '876-555-3333');
  assert.strictEqual(fee.address, '9 Main St', 'a field the dashboard never held survives');
});

test('syncTwinFields: the more recently edited record wins, and money is never touched', function () {
  var stale = { name: 'Old Name', email: 'old@x.com', lastModified: '2026-01-01T00:00:00Z' };
  var fresh = { name: 'New Name', email: 'new@x.com', tuitionFee: 28000, totalPaid: 20000,
                balance: 8000, status: 'Partial Payment', updatedAt: '2026-06-01T00:00:00Z' };
  assert.deepStrictEqual(Core.syncTwinFields(stale, fresh, 'lms->fee'), [], 'stale side cannot overwrite');
  assert.strictEqual(fresh.name, 'New Name');
  Core.syncTwinFields(fresh, stale, 'fee->lms');
  assert.strictEqual(stale.name, 'New Name', 'the newer edit propagates');
  assert.strictEqual(stale.tuitionFee, undefined, 'fee/money fields stay out of the dashboard');
  assert.strictEqual(stale.balance, undefined);
  assert.strictEqual(stale.status, undefined);
});

test('syncTwinFields: converges — a second pass has nothing left to do', function () {
  var lms = { name: 'John Smith', email: 'j@x.com', lastModified: '2026-06-01T00:00:00Z' };
  var fee = { name: 'Jon Smith', createdAt: '2026-01-01T00:00:00Z' };
  assert.ok(Core.syncTwinFields(lms, fee, 'lms->fee').length > 0);
  fee.updatedAt = lms.lastModified;
  assert.deepStrictEqual(Core.syncTwinFields(lms, fee, 'lms->fee'), []);
  assert.deepStrictEqual(Core.syncTwinFields(fee, lms, 'fee->lms'), [], 'and no bounce back');
});

console.log('\nAll ' + passed + ' tests passed.');
