/* Builds PASTE-ALL-IN-ONE.gs — the single file an operator pastes into a
   blank Apps Script project (README-DEPLOY step 1). Concatenates
   schemas.js + broker-core.js + Code.gs in dependency order with a banner.
   Run after changing any of the three:  node megadata/broker-appsscript/build-paste.js
   A drift test (megadata-glue) fails if the committed artifact is stale. */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const PARTS = [
  ['megadata/schemas.js', 'canonical serialization, ids, event registry'],
  ['megadata/broker-core.js', 'validation, numbering, hash chain'],
  ['megadata/broker-appsscript/Code.gs', 'Apps Script I/O glue (web app + Drive)']
];

function build() {
  let out = [
    '/* ============================================================================',
    ' * CESTIS MegaData Broker — ALL-IN-ONE Apps Script file.',
    ' * GENERATED by megadata/broker-appsscript/build-paste.js — do not edit here;',
    ' * edit the source files and rebuild.',
    ' *',
    ' * DEPLOY (README-DEPLOY.md): paste this ENTIRE file into a blank project at',
    ' * script.new (replace the default myFunction stub), set Script Properties',
    ' * HMAC_SECRET and MEGADATA_FOLDER_ID, then Deploy → New deployment → Web app',
    ' * (Execute as: Me / Access: Anyone with the link).',
    ' * ==========================================================================*/',
    ''
  ].join('\n');
  for (const [rel, what] of PARTS) {
    out += '\n/* ======== ' + rel + ' — ' + what + ' ======== */\n';
    out += fs.readFileSync(path.join(ROOT, rel), 'utf8');
  }
  return out;
}

const artifact = path.join(__dirname, 'PASTE-ALL-IN-ONE.gs');
if (module === require.main) {
  fs.writeFileSync(artifact, build());
  console.log('wrote ' + path.relative(ROOT, artifact) + ' (' + build().length + ' bytes)');
}
module.exports = { build, artifact };
