/* ============================================================================
 * CESTIS MegaData Broker — ALL-IN-ONE Apps Script file.
 * GENERATED by megadata/broker-appsscript/build-paste.js — do not edit here;
 * edit the source files and rebuild.
 *
 * DEPLOY (README-DEPLOY.md): paste this ENTIRE file into a blank project at
 * script.new (replace the default myFunction stub), set Script Properties
 * HMAC_SECRET and MEGADATA_FOLDER_ID, then Deploy → New deployment → Web app
 * (Execute as: Me / Access: Anyone with the link).
 * ==========================================================================*/

/* ======== megadata/schemas.js — canonical serialization, ids, event registry ======== */
/* MegaData — canonical serialization, event envelope, and schema validation.
   Phase 5 step 1. Runs in the browser (window.MegaData) and Node (module.exports).
   Design contract: docs/02-MEGADATA-ARCHITECTURE.md §3–§6; principles P2/P4/P5/P8/P11.

   Everything durable is an EVENT with this envelope; money is always integer
   minor units; timestamps are UTC ISO strings; ordering is broker `seq`, never
   client clocks. The canonical serialization here is the one used for content
   hashes and for every byte-equality gate in Phase 6 — change it and every
   stored hash breaks, so it is versioned by the envelope `v`. */
(function (root, factory) {
  var api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.MegaData = Object.assign(root.MegaData || {}, api);
})(typeof window !== 'undefined' ? window : globalThis, function () {
  'use strict';

  var ENVELOPE_V = 1;

  /* ---------- canonical serialization (P7/P11) ---------- */
  // Deterministic: sorted keys, no undefined, no NaN/Infinity, no floats where
  // a 'minor' amount is expected (validators enforce that; canon just refuses
  // non-finite numbers outright).
  function canon(value) {
    if (value === null) return 'null';
    var t = typeof value;
    if (t === 'number') {
      if (!isFinite(value)) throw new Error('canon: non-finite number');
      if (Object.is(value, -0)) value = 0;
      return JSON.stringify(value);
    }
    if (t === 'boolean' || t === 'string') return JSON.stringify(value);
    if (Array.isArray(value)) return '[' + value.map(canon).join(',') + ']';
    if (t === 'object') {
      var keys = Object.keys(value).filter(function (k) { return value[k] !== undefined; }).sort();
      return '{' + keys.map(function (k) { return JSON.stringify(k) + ':' + canon(value[k]); }).join(',') + '}';
    }
    throw new Error('canon: unsupported type ' + t);
  }

  /* ---------- hashing (async API in every runtime; three backends) ---------- */
  var nodeCrypto = null;
  try { if (typeof module !== 'undefined') nodeCrypto = require('crypto'); } catch (e) {}
  function sha256Hex(str) {
    // Apps Script (the broker): synchronous digest via Utilities — resolves
    // immediately, so Code.gs's promise-draining loop settles in one pass.
    if (typeof Utilities !== 'undefined' && Utilities.computeDigest) {
      var bytes = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, str, Utilities.Charset.UTF_8);
      var hex = '';
      for (var i = 0; i < bytes.length; i++) { hex += ((bytes[i] & 0xff) | 0x100).toString(16).slice(1); }
      return Promise.resolve(hex);
    }
    if (nodeCrypto) return Promise.resolve(nodeCrypto.createHash('sha256').update(str, 'utf8').digest('hex'));
    var enc = new TextEncoder().encode(str);
    return crypto.subtle.digest('SHA-256', enc).then(function (buf) {
      return Array.prototype.map.call(new Uint8Array(buf), function (b) {
        return b.toString(16).padStart(2, '0');
      }).join('');
    });
  }

  /* ---------- ids (P5: minted, never derived from meaning) ---------- */
  function randHex(n) {
    var bytes;
    if (nodeCrypto) bytes = nodeCrypto.randomBytes(n);
    else if (typeof crypto !== 'undefined' && crypto.getRandomValues) { bytes = new Uint8Array(n); crypto.getRandomValues(bytes); }
    else throw new Error('no CSPRNG in this runtime — the broker validates and numbers events; it never mints ids');
    return Array.prototype.map.call(bytes, function (b) { return b.toString(16).padStart(2, '0'); }).join('');
  }
  // Time-ordered unique id: ms timestamp base36 + 10 random bytes.
  function mintId(prefix, nowMs) {
    var ts = (nowMs != null ? nowMs : Date.now()).toString(36).padStart(9, '0');
    return prefix + '_' + ts + randHex(10);
  }
  // Migration ids are DETERMINISTIC so re-runs converge (P10).
  function migrationEventId(srcFileId, srcPath, transformV) {
    return sha256Hex([srcFileId, srcPath, 'v' + transformV].join('|')).then(function (h) {
      return 'evt_m' + h.slice(0, 24);
    });
  }

  /* ---------- field validators (compact DSL, P8) ---------- */
  var RE = {
    date: /^\d{4}-\d{2}-\d{2}$/,
    iso: /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,3})?Z$/,
    fy: /^\d{4}\/\d{4}$/
  };
  function checkField(spec, val, path, errors) {
    if (val === undefined || val === null) {
      if (spec.required) errors.push(path + ': required');
      return;
    }
    var t = spec.t;
    if (t === 'minor') { // money: integer minor units only (P4)
      if (typeof val !== 'number' || !Number.isInteger(val)) errors.push(path + ': must be integer minor units');
      else if (spec.positive && val <= 0) errors.push(path + ': must be > 0');
    } else if (t === 'int') {
      if (!Number.isInteger(val)) errors.push(path + ': must be integer');
    } else if (t === 'string') {
      if (typeof val !== 'string') errors.push(path + ': must be string');
      else if (spec.nonEmpty && !val.trim()) errors.push(path + ': must be non-empty');
    } else if (t === 'bool') {
      if (typeof val !== 'boolean') errors.push(path + ': must be boolean');
    } else if (t === 'date') {
      if (typeof val !== 'string' || !RE.date.test(val)) errors.push(path + ': must be YYYY-MM-DD');
    } else if (t === 'iso') {
      if (typeof val !== 'string' || !RE.iso.test(val)) errors.push(path + ': must be UTC ISO-8601 (…Z)');
    } else if (t === 'fy') {
      if (typeof val !== 'string' || !RE.fy.test(val)) errors.push(path + ': must be YYYY/YYYY fiscal year');
    } else if (t === 'enum') {
      if (spec.values.indexOf(val) === -1) errors.push(path + ': must be one of ' + spec.values.join('|'));
    } else if (t === 'id') {
      if (typeof val !== 'string' || val.indexOf(spec.prefix + '_') !== 0) errors.push(path + ': must be a ' + spec.prefix + '_ id');
    } else if (t === 'eventId') {
      if (typeof val !== 'string' || val.indexOf('evt_') !== 0) errors.push(path + ': must be an evt_ id');
    } else if (t === 'array') {
      if (!Array.isArray(val)) { errors.push(path + ': must be array'); return; }
      if (spec.min != null && val.length < spec.min) errors.push(path + ': needs >= ' + spec.min + ' items');
      if (spec.items) val.forEach(function (item, i) { checkObject(spec.items, item, path + '[' + i + ']', errors); });
    } else if (t === 'object') {
      checkObject(spec.fields || {}, val, path, errors);
    } else if (t === 'any') {
      /* free-form, canon() still constrains it at hash time */
    } else {
      errors.push(path + ': unknown validator ' + t);
    }
  }
  function checkObject(fields, obj, path, errors) {
    if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) { errors.push(path + ': must be object'); return; }
    Object.keys(fields).forEach(function (k) { checkField(fields[k], obj[k], path + '.' + k, errors); });
    if (fields.__closed) {
      Object.keys(obj).forEach(function (k) {
        if (!(k in fields)) errors.push(path + '.' + k + ': unknown field');
      });
    }
  }

  /* ---------- event type registry (docs/02 §5) ----------
     entity: the entity kind the event is anchored to (its id in envelope.entity.id).
     creates: event mints the entity (broker registers it in the integrity index).
     needsNumber: broker-assigned number series (docs/02 §2).
     payload: field specs. Stateful rules live in broker-core (P8). */
  var VIREMENT_LINE = { fromCategoryId: { t: 'string', required: true, nonEmpty: true }, toCategoryId: { t: 'string', required: true, nonEmpty: true }, amountMinor: { t: 'minor', required: true, positive: true } };
  var REGISTRY = {
    // --- people & enrolment (P3) ---
    'person.registered':      { entity: 'person', creates: true, payload: { names: { t: 'object', required: true, fields: { full: { t: 'string', required: true, nonEmpty: true } } }, dob: { t: 'date' }, gender: { t: 'string' }, nationalId: { t: 'string' }, contacts: { t: 'object' }, guardians: { t: 'array' } } },
    'person.corrected':       { entity: 'person', payload: { diff: { t: 'object', required: true }, reason: { t: 'string', required: true, nonEmpty: true } } },
    'person.merged':          { entity: 'person', payload: { loserId: { t: 'id', prefix: 'per', required: true }, evidence: { t: 'any', required: true }, tier: { t: 'enum', values: ['exact-id', 'strong-identifiers', 'human'], required: true } } },
    'person.tombstoned':      { entity: 'person', payload: { reason: { t: 'string', required: true, nonEmpty: true } } },
    'programme.defined':      { entity: 'programme', creates: true, payload: { name: { t: 'string', required: true, nonEmpty: true }, level: { t: 'string' }, nvqCode: { t: 'string' }, aliases: { t: 'array' } } },
    'intake.opened':          { entity: 'intake', creates: true, refs: { programme: 'programme' }, payload: { label: { t: 'string', required: true, nonEmpty: true }, start: { t: 'date', required: true }, end: { t: 'date' }, fiscalYear: { t: 'fy', required: true } } },
    'enrolment.created':      { entity: 'enrolment', creates: true, refs: { person: 'person', intake: 'intake' }, payload: { enrolledAt: { t: 'date', required: true } } },
    'enrolment.statusChanged':{ entity: 'enrolment', payload: { to: { t: 'enum', values: ['active', 'completed', 'withdrawn', 'nyc'], required: true }, reason: { t: 'string', required: true, nonEmpty: true } } },
    'enrolment.transferred':  { entity: 'enrolment', refs: { toIntake: 'intake' }, payload: { reason: { t: 'string', required: true, nonEmpty: true } } },
    // --- fees (P4) ---
    'fees.schedule.set':      { entity: 'feeSchedule', creates: true, refs: { intake: 'intake' }, payload: { totalMinor: { t: 'minor', required: true }, terms: { t: 'array', required: true, min: 1, items: { no: { t: 'int', required: true }, amountMinor: { t: 'minor', required: true }, dueDate: { t: 'date' } } } } },
    'fees.charge.assessed':   { entity: 'enrolment', payload: { termNo: { t: 'int', required: true }, amountMinor: { t: 'minor', required: true, positive: true }, dueDate: { t: 'date' } } },
    'fees.payment.recorded':  { entity: 'enrolment', needsNumber: 'receipt', payload: { amountMinor: { t: 'minor', required: true, positive: true }, method: { t: 'enum', values: ['cash', 'cheque', 'transfer', 'card', 'other'], required: true }, date: { t: 'date', required: true }, reference: { t: 'string' }, receiptNo: { t: 'string' }, legacyReceiptNo: { t: 'string' } } },
    'fees.payment.reversed':  { entity: 'enrolment', payload: { paymentEventId: { t: 'eventId', required: true }, reason: { t: 'string', required: true, nonEmpty: true } } },
    'fees.adjustment.applied':{ entity: 'enrolment', payload: { amountMinor: { t: 'minor', required: true }, kind: { t: 'enum', values: ['waiver', 'discount', 'writeoff', 'correction'], required: true }, reason: { t: 'string', required: true, nonEmpty: true } } },
    // --- cashbook / finance ---
    // NOTE (client decision D11, 2026-08-05): the cashbook is a SEPARATE book from
    // the school-fee ledger — deliberately no fee-payment link field here.
    'cashbook.entry.recorded':{ entity: 'cashbookEntry', creates: true, payload: { fy: { t: 'fy', required: true }, q: { t: 'int', required: true }, date: { t: 'date', required: true }, kind: { t: 'enum', values: ['income', 'expense'], required: true }, categoryId: { t: 'string', required: true, nonEmpty: true }, amountMinor: { t: 'minor', required: true, positive: true }, chequeNo: { t: 'string' }, payee: { t: 'string' }, legacyTxnId: { t: 'string' }, supersedes: { t: 'string' } } },
    'cashbook.cheque.voided': { entity: 'cashbookEntry', payload: { reason: { t: 'string', required: true, nonEmpty: true } } },
    'cashbook.quarter.opened':{ entity: 'cashbookQuarter', creates: true, payload: { fy: { t: 'fy', required: true }, q: { t: 'int', required: true }, openingBalanceMinor: { t: 'minor', required: true } } },
    // budget.set is a REPLACE, not a create: each set supersedes the
    // quarter's lines wholesale (the entity autovivifies on first set), so a
    // live budget edit is an ordinary event and every version is audited.
    'budget.set':             { entity: 'budget', payload: { fy: { t: 'fy', required: true }, q: { t: 'int', required: true }, lines: { t: 'array', required: true, items: { categoryId: { t: 'string', required: true, nonEmpty: true }, sectionId: { t: 'string' }, amountMinor: { t: 'minor', required: true } } } } },
    'virement.requested':     { entity: 'virement', creates: true, payload: { fy: { t: 'fy', required: true }, q: { t: 'int', required: true }, lines: { t: 'array', required: true, min: 1, items: VIREMENT_LINE }, requestedBy: { t: 'string', required: true, nonEmpty: true } } },
    'virement.decided':       { entity: 'virement', payload: { decision: { t: 'enum', values: ['approved', 'rejected'], required: true }, note: { t: 'string' }, decidedBy: { t: 'string' }, decidedOn: { t: 'date' } } },
    'findoc.issued':          { entity: 'findoc', creates: true, needsNumber: 'findoc', payload: { kind: { t: 'enum', values: ['invoice', 'quote', 'po', 'voucher'], required: true }, number: { t: 'string' }, doc: { t: 'any', required: true } } },
    'findoc.superseded':      { entity: 'findoc', payload: { diff: { t: 'object', required: true }, reason: { t: 'string', required: true, nonEmpty: true } } },
    'findoc.voided':          { entity: 'findoc', payload: { reason: { t: 'string', required: true, nonEmpty: true } } },
    // --- payroll & time ---
    'payroll.run.recorded':   { entity: 'payrollRun', creates: true, payload: { month: { t: 'string', required: true, nonEmpty: true }, rateTableV: { t: 'int', required: true }, lines: { t: 'array', required: true, min: 1, items: { staffId: { t: 'id', prefix: 'stf', required: true }, grossMinor: { t: 'minor', required: true }, deductionsMinor: { t: 'object', required: true }, netMinor: { t: 'minor', required: true } } } } },
    'payroll.line.corrected': { entity: 'payrollRun', payload: { staffId: { t: 'id', prefix: 'stf', required: true }, diff: { t: 'object', required: true }, reason: { t: 'string', required: true, nonEmpty: true } } },
    'time.clockedIn':         { entity: 'timeRecord', creates: true, refs: { staff: 'staff' }, payload: { at: { t: 'iso', required: true } } },
    'time.clockedOut':        { entity: 'timeRecord', payload: { at: { t: 'iso', required: true } } },
    'time.corrected':         { entity: 'timeRecord', payload: { diff: { t: 'object', required: true }, reason: { t: 'string', required: true, nonEmpty: true } } },
    // --- attendance & assessment ---
    'attendance.marked':      { entity: 'enrolment', payload: { date: { t: 'date', required: true }, status: { t: 'enum', values: ['present', 'absent', 'late'], required: true }, sessionId: { t: 'string' } } },
    'attendance.corrected':   { entity: 'enrolment', payload: { markEventId: { t: 'eventId', required: true }, newStatus: { t: 'enum', values: ['present', 'absent', 'late'], required: true }, reason: { t: 'string', required: true, nonEmpty: true } } },
    'assessment.result.recorded':  { entity: 'enrolment', payload: { examId: { t: 'string', required: true, nonEmpty: true }, scorePct: { t: 'int' }, detail: { t: 'any' } } },
    'assessment.result.overridden':{ entity: 'enrolment', payload: { resultEventId: { t: 'eventId', required: true }, grade: { t: 'any', required: true }, reason: { t: 'string', required: true, nonEmpty: true } } },
    // --- certification ---
    'cert.approved':          { entity: 'enrolment', payload: {} },
    'cert.issued':            { entity: 'enrolment', needsNumber: 'cert', payload: { certNo: { t: 'string' }, templateId: { t: 'string' } } },
    'cert.collected':         { entity: 'enrolment', payload: {} },
    // --- adjudication, Tier B docs, admin ---
    'identity.adjudicated':   { entity: 'adjudication', payload: { itemId: { t: 'string', required: true, nonEmpty: true }, decision: { t: 'string', required: true, nonEmpty: true }, note: { t: 'string' } } },
    'doc.upserted':           { entity: 'doc', payload: { kind: { t: 'string', required: true, nonEmpty: true }, diff: { t: 'object', required: true }, reason: { t: 'string' } } },
    'doc.tombstoned':         { entity: 'doc', payload: { kind: { t: 'string', required: true, nonEmpty: true }, reason: { t: 'string', required: true, nonEmpty: true } } },
    'admin.noteAppended':     { entity: 'doc', payload: { text: { t: 'string', required: true, nonEmpty: true }, entityRef: { t: 'string' } } }
  };
  Object.keys(REGISTRY).forEach(function (t) { REGISTRY[t].schemaV = REGISTRY[t].schemaV || 1; });

  /* ---------- envelope build & validate ---------- */
  var ENVELOPE_FIELDS = {
    v: { t: 'int', required: true }, id: { t: 'eventId', required: true },
    type: { t: 'string', required: true, nonEmpty: true }, schemaV: { t: 'int', required: true },
    entity: { t: 'object', required: true, fields: { kind: { t: 'string', required: true, nonEmpty: true }, id: { t: 'string', required: true, nonEmpty: true } } },
    refs: { t: 'object' }, payload: { t: 'object', required: true },
    actor: { t: 'object', required: true, fields: { account: { t: 'string' }, name: { t: 'string', required: true, nonEmpty: true }, role: { t: 'string', required: true, nonEmpty: true }, device: { t: 'string' } } },
    at: { t: 'iso', required: true }, source: { t: 'string', required: true, nonEmpty: true },
    cause: { t: 'string' }, corr: { t: 'string' }, prov: { t: 'object' }, hash: { t: 'string' }
  };

  // The hash covers the canonical form minus broker-assigned / self fields.
  // `assigned` carries broker-issued numbers (receiptNo/certNo/…) so the
  // client-computed hash stays valid after append (docs/02 §2, §9).
  var BROKER_FIELDS = { seq: 1, brokerAt: 1, hash: 1, assigned: 1 };
  function hashBasis(evt) {
    var copy = {};
    Object.keys(evt).forEach(function (k) {
      if (!BROKER_FIELDS[k]) copy[k] = evt[k];
    });
    return canon(copy);
  }

  function validateEvent(evt) {
    var errors = [];
    checkObject(ENVELOPE_FIELDS, evt, 'event', errors);
    if (errors.length) return { ok: false, errors: errors };
    var reg = REGISTRY[evt.type];
    if (!reg) return { ok: false, errors: ['event.type: unknown type ' + evt.type] };
    if (evt.schemaV !== reg.schemaV) errors.push('event.schemaV: expected ' + reg.schemaV + ' for ' + evt.type);
    if (evt.entity.kind !== reg.entity) errors.push('event.entity.kind: expected ' + reg.entity + ' for ' + evt.type);
    checkObject(reg.payload, evt.payload, 'payload', errors);
    if (reg.refs) {
      Object.keys(reg.refs).forEach(function (r) {
        if (!evt.refs || typeof evt.refs[r] !== 'string' || !evt.refs[r]) errors.push('refs.' + r + ': required for ' + evt.type);
      });
    }
    return { ok: errors.length === 0, errors: errors };
  }

  // Build a full event (mints id, stamps hash). opts: {id?, at?, entityId?, refs, cause, corr, prov, nowMs?}
  function buildEvent(type, entityId, payload, actor, source, opts) {
    opts = opts || {};
    var reg = REGISTRY[type];
    if (!reg) return Promise.reject(new Error('unknown event type ' + type));
    var evt = {
      v: ENVELOPE_V,
      id: opts.id || mintId('evt', opts.nowMs),
      type: type, schemaV: reg.schemaV,
      entity: { kind: reg.entity, id: entityId },
      refs: opts.refs || {}, payload: payload || {},
      actor: actor, at: opts.at || new Date(opts.nowMs != null ? opts.nowMs : Date.now()).toISOString(),
      source: source,
      cause: opts.cause || null, corr: opts.corr || null,
      prov: opts.prov || null
    };
    var v = validateEvent(evt);
    if (!v.ok) return Promise.reject(Object.assign(new Error('invalid event: ' + v.errors.join('; ')), { errors: v.errors }));
    return sha256Hex(hashBasis(evt)).then(function (h) { evt.hash = 'sha256:' + h; return evt; });
  }

  function verifyEventHash(evt) {
    return sha256Hex(hashBasis(evt)).then(function (h) { return evt.hash === 'sha256:' + h; });
  }

  return {
    ENVELOPE_V: ENVELOPE_V, REGISTRY: REGISTRY,
    canon: canon, sha256Hex: sha256Hex,
    mintId: mintId, migrationEventId: migrationEventId,
    validateEvent: validateEvent, buildEvent: buildEvent,
    verifyEventHash: verifyEventHash, hashBasis: hashBasis
  };
});

/* ======== megadata/broker-core.js — validation, numbering, hash chain ======== */
/* MegaData — broker core (Phase 5 step 2). Pure logic, no I/O.
   This exact module runs in three hosts with different glue:
     1. Node local broker (tests, and the Offline System's LAN server later);
     2. the Apps Script web app (step 7 glue; LockService + Drive around it);
     3. the migration CLI (bootstrap appends through the same gates).
   Contract: docs/02-MEGADATA-ARCHITECTURE.md §9. It is the ONLY thing that
   assigns `seq` and number series, and NOTHING invalid is ever appended (P8).
   Everything here is deterministic given (state, events, now) — replays and
   retries converge (P10): a duplicate event id returns the ORIGINAL ack. */
(function (root, factory) {
  var MD = (typeof module !== 'undefined' && module.exports) ? require('./schemas.js') : root.MegaData;
  var api = factory(MD);
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.MegaData = Object.assign(root.MegaData || {}, api);
})(typeof window !== 'undefined' ? window : globalThis, function (MD) {
  'use strict';

  var SERIES_PREFIX = { receipt: 'R-', cert: 'CT-', invoice: 'INV-', quote: 'QUO-', po: 'PO-', voucher: 'VOU-' };
  function pad6(n) { return String(n).padStart(6, '0'); }

  // Entity kinds that auto-vivify on first event (Tier B docs, queue items,
  // and budgets — budget.set is a replace whose first set brings the
  // quarter's budget into existence).
  var AUTOVIVIFY = { doc: 1, adjudication: 1, budget: 1 };
  // Enrolment statuses that release a person for tombstoning.
  var RELEASED = { withdrawn: 1, completed: 1 };

  function createBrokerState() {
    return {
      seq: 0,
      events: [],                 // acked events in seq order (the log)
      ackById: {},                // eventId → { seq, assigned }
      series: { receipt: 0, cert: 0, invoice: 0, quote: 0, po: 0, voucher: 0 },
      chain: 'genesis',           // running hash chain over event hashes (P11)
      segments: [],               // { n, firstSeq, lastSeq, count, prevChain, chain }
      gates: { bootstrap: 'not-started', maintenance: false },
      index: {
        entities: {},             // kind → id → { alive, mergedInto?, status? }
        personEnrolments: {},     // personId → [enrolmentId]
        payments: {},             // paymentEventId → { enrolmentId, amountMinor, reversedBy }
        eventsById: {}            // eventId → { type, entityId } (for supersession refs)
      }
    };
  }

  function ent(state, kind, id) {
    var k = state.index.entities[kind];
    return (k && k[id]) || null;
  }
  function putEnt(state, kind, id, rec) {
    (state.index.entities[kind] = state.index.entities[kind] || {})[id] = rec;
  }

  /* Stateful validation (P8). Returns [] when clean. */
  function stateErrors(state, evt) {
    var reg = MD.REGISTRY[evt.type];
    var errs = [];
    var kind = evt.entity.kind, id = evt.entity.id;
    var existing = ent(state, kind, id);
    if (reg.creates) {
      if (existing) errs.push('entity ' + kind + '/' + id + ' already exists');
    } else if (!AUTOVIVIFY[kind]) {
      if (!existing) errs.push('entity ' + kind + '/' + id + ' does not exist');
      else if (!existing.alive) errs.push('entity ' + kind + '/' + id + ' is tombstoned/merged');
    }
    if (reg.refs) {
      Object.keys(reg.refs).forEach(function (r) {
        var refId = evt.refs && evt.refs[r];
        var refEnt = refId && ent(state, reg.refs[r], refId);
        if (!refEnt) errs.push('ref ' + r + ' (' + reg.refs[r] + '/' + refId + ') does not exist');
        else if (!refEnt.alive) errs.push('ref ' + r + ' (' + reg.refs[r] + '/' + refId + ') is not alive');
      });
    }
    switch (evt.type) {
      case 'person.tombstoned': {
        var enrols = state.index.personEnrolments[id] || [];
        var live = enrols.filter(function (eid) {
          var e = ent(state, 'enrolment', eid);
          return e && e.alive && !RELEASED[e.status || 'active'];
        });
        if (live.length) errs.push('person has ' + live.length + ' active enrolment(s); withdraw/complete them first');
        break;
      }
      case 'person.merged': {
        var loser = ent(state, 'person', evt.payload.loserId);
        if (!loser) errs.push('merge loser does not exist');
        else if (!loser.alive) errs.push('merge loser already tombstoned/merged');
        if (evt.payload.loserId === id) errs.push('cannot merge a person into themselves');
        break;
      }
      case 'fees.payment.reversed': {
        var p = state.index.payments[evt.payload.paymentEventId];
        if (!p) errs.push('paymentEventId is not a recorded payment');
        else {
          if (p.enrolmentId !== id) errs.push('payment belongs to a different enrolment');
          if (p.reversedBy) errs.push('payment already reversed by ' + p.reversedBy);
        }
        break;
      }
      case 'cashbook.cheque.voided':
      case 'findoc.superseded':
      case 'findoc.voided': {
        // The entity itself must exist (checked above); nothing more stateful.
        break;
      }
      case 'attendance.corrected': {
        var m = state.index.eventsById[evt.payload.markEventId];
        if (!m || m.type !== 'attendance.marked') errs.push('markEventId is not an attendance.marked event');
        else if (m.entityId !== id) errs.push('attendance mark belongs to a different enrolment');
        break;
      }
      case 'assessment.result.overridden': {
        var rr = state.index.eventsById[evt.payload.resultEventId];
        if (!rr || rr.type !== 'assessment.result.recorded') errs.push('resultEventId is not a recorded result');
        else if (rr.entityId !== id) errs.push('result belongs to a different enrolment');
        break;
      }
    }
    return errs;
  }

  /* Apply an accepted event to the integrity index. */
  function indexApply(state, evt) {
    var reg = MD.REGISTRY[evt.type];
    var kind = evt.entity.kind, id = evt.entity.id;
    if (reg.creates && !ent(state, kind, id)) putEnt(state, kind, id, { alive: true });
    if (AUTOVIVIFY[kind] && !ent(state, kind, id)) putEnt(state, kind, id, { alive: true });
    state.index.eventsById[evt.id] = { type: evt.type, entityId: id };
    switch (evt.type) {
      case 'enrolment.created': {
        var pid = evt.refs.person;
        (state.index.personEnrolments[pid] = state.index.personEnrolments[pid] || []).push(id);
        putEnt(state, 'enrolment', id, { alive: true, status: 'active', personId: pid });
        break;
      }
      case 'enrolment.statusChanged': {
        var e = ent(state, 'enrolment', id); if (e) e.status = evt.payload.to;
        break;
      }
      case 'person.tombstoned':
      case 'doc.tombstoned': {
        var t = ent(state, kind, id); if (t) t.alive = false;
        break;
      }
      case 'person.merged': {
        var loser = ent(state, 'person', evt.payload.loserId);
        if (loser) { loser.alive = false; loser.mergedInto = id; }
        break;
      }
      case 'fees.payment.recorded': {
        state.index.payments[evt.id] = { enrolmentId: id, amountMinor: evt.payload.amountMinor, reversedBy: null };
        break;
      }
      case 'fees.payment.reversed': {
        var p = state.index.payments[evt.payload.paymentEventId];
        if (p) p.reversedBy = evt.id;
        break;
      }
    }
  }

  function assignNumbers(state, evt) {
    var reg = MD.REGISTRY[evt.type];
    if (!reg.needsNumber) return null;
    var series;
    if (reg.needsNumber === 'findoc') series = evt.payload.kind;   // invoice/quote/po/voucher
    else series = reg.needsNumber;                                  // receipt/cert
    // Legacy imports carry their own numbers — never renumber history. For
    // receipts that includes the PRESERVED legacy number (legacyReceiptNo,
    // the field bootstrap and the fee bridge write): the number on the paper
    // receipt a parent holds stays the payment's number for good.
    var presentField = series === 'receipt' ? 'receiptNo' : series === 'cert' ? 'certNo' : 'number';
    if (evt.payload && evt.payload[presentField]) return null;
    if (series === 'receipt' && evt.payload && evt.payload.legacyReceiptNo) return null;
    state.series[series] = (state.series[series] || 0) + 1;
    var num = SERIES_PREFIX[series] + pad6(state.series[series]);
    var field = series === 'receipt' ? 'receiptNo' : series === 'cert' ? 'certNo' : 'number';
    var out = {}; out[field] = num;
    return out;
  }

  function createBroker(initialState) {
    var state = initialState || createBrokerState();

    // append: validate everything first, then commit ALL-OR-NOTHING per batch.
    // A batch is one client outbox drain; partial acceptance would leave the
    // client guessing, so any invalid event fails the whole batch with named
    // per-event errors (quarantine happens client-side / migration-side).
    function append(req, opts) {
      var events = (req && req.events) || [];
      var now = (opts && opts.nowIso) || new Date().toISOString();
      var acks = {}, errors = {}, fresh = [];
      var chainP = Promise.resolve();

      // Pass 1 — validate against a SCRATCH copy of the index, applying each
      // event as it validates, so within-batch causal chains work (create a
      // person and enrol them in one outbox drain). The real state is only
      // touched in pass 2, keeping the batch all-or-nothing.
      var scratch = { index: JSON.parse(JSON.stringify(state.index)) };
      for (var i = 0; i < events.length; i++) {
        var evt = events[i];
        if (state.ackById[evt.id]) { acks[evt.id] = state.ackById[evt.id]; continue; }
        var v = MD.validateEvent(evt);
        var errs = v.ok ? stateErrors(scratch, evt) : v.errors;
        if (errs.length) errors[evt.id] = errs;
        else { indexApply(scratch, evt); fresh.push(evt); }
      }
      if (Object.keys(errors).length) {
        return Promise.resolve({ ok: false, acks: {}, errors: errors, head: head() });
      }

      // Pass 2 — verify hashes, then commit in order.
      return Promise.all(fresh.map(function (evt) { return MD.verifyEventHash(evt); }))
        .then(function (verdicts) {
          verdicts.forEach(function (good, i) { if (!good) errors[fresh[i].id] = ['content hash does not verify']; });
          if (Object.keys(errors).length) return { ok: false, acks: {}, errors: errors, head: head() };
          var segFirst = state.seq + 1;
          fresh.forEach(function (evt) {
            var stored = Object.assign({}, evt);
            stored.seq = ++state.seq;
            stored.brokerAt = now;
            var assigned = assignNumbers(state, stored);
            if (assigned) stored.assigned = assigned;
            state.events.push(stored);
            indexApply(state, stored);
            state.ackById[evt.id] = { seq: stored.seq, assigned: assigned || null };
            acks[evt.id] = state.ackById[evt.id];
            chainP = chainP.then(function () {
              return MD.sha256Hex(state.chain + '|' + stored.hash).then(function (h) { state.chain = h; });
            });
          });
          return chainP.then(function () {
            if (fresh.length) {
              state.segments.push({
                n: state.segments.length + 1, firstSeq: segFirst, lastSeq: state.seq,
                count: fresh.length, chain: state.chain
              });
            }
            return { ok: true, acks: acks, errors: {}, head: head() };
          });
        });
    }

    function pull(req) {
      var since = (req && req.sinceSeq) || 0;
      var max = (req && req.max) || 500;
      var out = [];
      for (var i = 0; i < state.events.length && out.length < max; i++) {
        if (state.events[i].seq > since) out.push(state.events[i]);
      }
      return Promise.resolve({ events: out, head: head() });
    }

    function head() { return { seq: state.seq, chain: state.chain }; }

    function gate(req) {
      if (req.op === 'get') return Promise.resolve({ gates: state.gates });
      if (req.op === 'setBootstrap') { state.gates.bootstrap = req.value; return Promise.resolve({ gates: state.gates }); }
      if (req.op === 'setMaintenance') { state.gates.maintenance = !!req.value; return Promise.resolve({ gates: state.gates }); }
      return Promise.reject(new Error('unknown gate op'));
    }

    // Verify the whole chain from the stored events (integrity tooling, P11).
    function verifyChain() {
      var chain = 'genesis', i = 0;
      function step() {
        if (i >= state.events.length) return Promise.resolve(chain === state.chain);
        var evt = state.events[i++];
        return MD.verifyEventHash(evt).then(function (good) {
          if (!good) return false;
          return MD.sha256Hex(chain + '|' + evt.hash).then(function (h) { chain = h; return step(); });
        });
      }
      return step();
    }

    return { append: append, pull: pull, headq: function () { return Promise.resolve(head()); }, gate: gate, verifyChain: verifyChain, _state: state };
  }

  return { createBroker: createBroker, createBrokerState: createBrokerState };
});

/* ======== megadata/broker-appsscript/Code.gs — Apps Script I/O glue (web app + Drive) ======== */
/* MegaData broker — Google Apps Script glue (Phase 5 step 7; docs/02 §9).
 *
 * ⚠ STATUS: NOT YET TESTED AGAINST LIVE APPS SCRIPT / DRIVE (spec 5.3: this
 * build environment has no Drive access). The pure logic it wraps
 * (broker-core.js) carries the full Node test suite; this file is the thin
 * I/O glue and must be smoke-tested at deployment using README-DEPLOY.md.
 *
 * DEPLOY: paste the full contents of megadata/schemas.js, then
 * megadata/broker-core.js, ABOVE this file's contents in one .gs project
 * (Apps Script has no require; the UMD headers no-op there and register on
 * globalThis.MegaData). Then follow README-DEPLOY.md.
 *
 * Script Properties (File → Project properties → Script properties):
 *   HMAC_SECRET         shared secret; the same value an admin enters once
 *                       per device in the app (never committed — public repo)
 *   MEGADATA_FOLDER_ID  Drive id of the MegaData master folder
 */
/* global MegaData, LockService, PropertiesService, DriveApp, ContentService, Utilities */

var STATE_FILE = 'broker-state.json';
var HEAD_FILE = 'head.json';

function jsonOut(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

function props() { return PropertiesService.getScriptProperties(); }
function folder() { return DriveApp.getFolderById(props().getProperty('MEGADATA_FOLDER_ID')); }

function findFile(fld, name) {
  var it = fld.getFilesByName(name);
  return it.hasNext() ? it.next() : null;
}
function readJsonFile(fld, name, dflt) {
  var f = findFile(fld, name);
  if (!f) return dflt;
  return JSON.parse(f.getBlob().getDataAsString());
}
function writeJsonFile(fld, name, obj) {
  // head/state are the broker's own files, single-writer under the lock —
  // setContent here is safe ONLY because of that lock (docs/02 §1).
  var text = JSON.stringify(obj);
  var f = findFile(fld, name);
  if (f) f.setContent(text); else fld.createFile(name, text, 'application/json');
}

function hmacOk(auth, payload) {
  var secret = props().getProperty('HMAC_SECRET') || '';
  var expected = sha256HexSync(secret + '|' + MegaData.canon(payload || {}));
  return auth === expected;
}
function sha256HexSync(str) {
  var raw = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, str, Utilities.Charset.UTF_8);
  return raw.map(function (b) { return ('0' + ((b + 256) % 256).toString(16)).slice(-2); }).join('');
}

function doGet() {
  return jsonOut({ ok: true, service: 'cestis-megadata-broker', version: 1 });
}

function doPost(e) {
  var req;
  try { req = JSON.parse(e.postData.contents); }
  catch (err) { return jsonOut({ error: 'body is not JSON' }); }
  if (!hmacOk(req.auth, req.payload)) return jsonOut({ error: 'auth failed' });

  var lock = LockService.getScriptLock();
  if (!lock.tryLock(25000)) return jsonOut({ error: 'busy', retryable: true });
  try {
    var fld = folder();
    var state = readJsonFile(fld, STATE_FILE, null) || MegaData.createBrokerState();
    var broker = MegaData.createBroker(state);
    var before = state.events.length;
    var result;
    switch (req.op) {
      case 'append': result = broker.append(req.payload, { nowIso: new Date().toISOString() }); break;
      case 'pull':   result = broker.pull(req.payload); break;
      case 'headq':  result = broker.headq(); break;
      case 'gate':   result = broker.gate(req.payload); break;
      default: return jsonOut({ error: 'unknown op ' + req.op });
    }
    // broker-core returns Promises; Apps Script's V8 runtime resolves them
    // synchronously here because sha256 falls back to… it does NOT: digest is
    // async in the core. So we drive the promise to completion:
    var out = null, err = null, done = false;
    result.then(function (r) { out = r; done = true; }, function (ex) { err = ex; done = true; });
    // V8 runtime: microtasks run when the call stack empties; Utilities.sleep
    // yields. Bounded wait:
    var waited = 0;
    while (!done && waited < 20000) { Utilities.sleep(50); waited += 50; }
    if (!done) return jsonOut({ error: 'internal timeout' });
    if (err) return jsonOut({ error: String(err && err.message || err) });

    if (req.op === 'append' && out.ok && state.events.length > before) {
      var fresh = state.events.slice(before);
      var segName = 'seg-' + ('000000' + state.segments.length).slice(-6)
        + '-' + fresh[0].seq + '-' + fresh[fresh.length - 1].seq + '.jsonl';
      fld.createFile(segName, fresh.map(function (ev) { return JSON.stringify(ev); }).join('\n'), 'application/json');
      writeJsonFile(fld, HEAD_FILE, { seq: state.seq, chain: state.chain, segments: state.segments, gates: state.gates });
    }
    if (req.op === 'append' || req.op === 'gate') writeJsonFile(fld, STATE_FILE, state);
    return jsonOut(out);
  } finally {
    lock.releaseLock();
  }
}
